---
database_name: "lib/image-catalog.db"
sources_name: "etc/focal-source.yaml"
template_directory: "templates"
no_remote_repository: "git@git.coolcompany.com:openstack/image-catalogs.git"
local_repository: "repository"
