---
database_name: "lib/image-catalog.db"
sources_name: "etc/image-sources.yaml"
template_directory: "templates"
remote_repository: "git@git.gadgetlab.de:openstack/image-catalogs.git"
local_repository: "repository"
